### ISSUE TITLE
Pure pursuit controller not steering

### ISSUE THREAD

**Issue by Rayman** [ros-planning/navigation2_tutorials#13]
Hi,

I'm following the navigation2 tutorial and and was testing the pure pursuit controller. It seems to me that the controllor is not steering. See the gif below.

#### Possible cause

The path is transformed only once (at `setPath`). This means the local goal is never updated. I think the path should be transformed at every `computeVelocityCommands` call.

![pure_pursuit_bug](https://user-images.githubusercontent.com/91969/98358011-59a89a80-2026-11eb-9c56-a08de48c716c.gif)

**Comment by SteveMacenski** [comment]
A PR to resolve would be appreciated. Keep in mind this was just tutorial code so I didn't really review it for functionality. I agree though that having a functional pure-pursuit controller would be helpful though for some users.

**Comment by Rayman** [comment]
I've fixed the 2 issues I found, I'll clean it up for a PR soon™
