### ISSUE TITLE
Building error nav2_straightline_planner

### ISSUE THREAD

**Issue by Kaiser-Wang** [ros-planning/navigation2_tutorials#21]
I'm following this tutorial: [https://navigation.ros.org/plugin_tutorials/docs/writing_new_nav2planner_plugin.html](url)
and trying to compile nav2_straightline_planner package in navigation2 workspace on ros2 foxy using following command line:
`colcon build --packages-select nav2_straightline_planner`

Then I received these errors:
<pre><font color="#3465A4"><b>~/navigation2_ws</b></font>$ colcon build --packages-select nav2_straightline_planner
Starting &gt;&gt;&gt; nav2_straightline_planner
--- stderr: nav2_straightline_planner                             
In file included from <b>/home/kai/navigation2_ws/src/navigation2/nav2_straightline_planner/src/straight_line_planner.cpp:46</b>:
<b>/home/kai/navigation2_ws/src/navigation2/nav2_straightline_planner/include/nav2_straightline_planner/straight_line_planner.hpp:67:8:</b> <font color="#CC0000"><b>error: </b></font>‘<b>void nav2_straightline_planner::StraightLine::configure(const WeakPtr&amp;, std::string, std::shared_ptr&lt;tf2_ros::Buffer&gt;, std::shared_ptr&lt;nav2_costmap_2d::Costmap2DROS&gt;)</b>’ marked ‘<b>override</b>’, but does not override
   67 |   void <font color="#CC0000"><b>configure</b></font>(
      |        <font color="#CC0000"><b>^~~~~~~~~</b></font>
In file included from <b>/opt/ros/foxy/include/class_loader/class_loader_core.hpp:57</b>,
                 from <b>/opt/ros/foxy/include/class_loader/class_loader.hpp:55</b>,
                 from <b>/opt/ros/foxy/include/class_loader/multi_library_class_loader.hpp:52</b>,
                 from <b>/opt/ros/foxy/include/pluginlib/class_loader.hpp:58</b>,
                 from <b>/home/kai/navigation2_ws/install/nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d_ros.hpp:53</b>,
                 from <b>/home/kai/navigation2_ws/install/nav2_core/include/nav2_core/global_planner.hpp:21</b>,
                 from <b>/home/kai/navigation2_ws/src/navigation2/nav2_straightline_planner/include/nav2_straightline_planner/straight_line_planner.hpp:51</b>,
                 from <b>/home/kai/navigation2_ws/src/navigation2/nav2_straightline_planner/src/straight_line_planner.cpp:46</b>:
/opt/ros/foxy/include/class_loader/meta_object.hpp: In instantiation of ‘<b>B* class_loader::impl::MetaObject&lt;C, B&gt;::create() const [with C = nav2_straightline_planner::StraightLine; B = nav2_core::GlobalPlanner]</b>’:
<b>/opt/ros/foxy/include/class_loader/meta_object.hpp:190:7:</b>   required from here
<b>/opt/ros/foxy/include/class_loader/meta_object.hpp:192:12:</b> <font color="#CC0000"><b>error: </b></font><b>invalid new-ex</b>pression of abstract class type ‘<b>nav2_straightline_planner::StraightLine</b>’
  192 |     return <font color="#CC0000"><b>new C</b></font>;
      |            <font color="#CC0000"><b>^~~~~</b></font>
In file included from <b>/home/kai/navigation2_ws/src/navigation2/nav2_straightline_planner/src/straight_line_planner.cpp:46</b>:
<b>/home/kai/navigation2_ws/src/navigation2/nav2_straightline_planner/include/nav2_straightline_planner/straight_line_planner.hpp:60:7:</b> <font color="#06989A"><b>note: </b></font>  because the following virtual functions are pure within ‘<b>nav2_straightline_planner::StraightLine</b>’:
   60 | class <font color="#06989A"><b>StraightLine</b></font> : public nav2_core::GlobalPlanner
      |       <font color="#06989A"><b>^~~~~~~~~~~~</b></font>
In file included from <b>/home/kai/navigation2_ws/src/navigation2/nav2_straightline_planner/include/nav2_straightline_planner/straight_line_planner.hpp:51</b>,
                 from <b>/home/kai/navigation2_ws/src/navigation2/nav2_straightline_planner/src/straight_line_planner.cpp:46</b>:
<b>/home/kai/navigation2_ws/install/nav2_core/include/nav2_core/global_planner.hpp:50:16:</b> <font color="#06989A"><b>note: </b></font>	‘<b>virtual void nav2_core::GlobalPlanner::configure(rclcpp_lifecycle::LifecycleNode::SharedPtr, std::string, std::shared_ptr&lt;tf2_ros::Buffer&gt;, std::shared_ptr&lt;nav2_costmap_2d::Costmap2DROS&gt;)</b>’
   50 |   virtual void <font color="#06989A"><b>configure</b></font>(
      |                <font color="#06989A"><b>^~~~~~~~~</b></font>
make[2]: *** [CMakeFiles/nav2_straightline_planner_plugin.dir/build.make:63: CMakeFiles/nav2_straightline_planner_plugin.dir/src/straight_line_planner.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/nav2_straightline_planner_plugin.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
Failed   &lt;&lt;&lt; nav2_straightline_planner [4.84s, exited with code 2]

Summary: 0 packages finished [5.09s]
  1 package failed: nav2_straightline_planner
  1 package had stderr output: nav2_straightline_planner</pre>

**Comment by SteveMacenski** [comment]
https://github.com/ros-planning/navigation2_tutorials/blob/master/nav2_straightline_planner/src/straight_line_planner.cpp#L52

These target ROS2 master branch, so your issue is that the WeakPtr supersedes the Foxy API with SharedPtr

**Comment by philison** [comment]
If you need additional information, have a look at how function overloading works in c++.  
[Function overloading explained](https://www.learncpp.com/cpp-tutorial/function-overloading/)

If you want to write a plugin that inherits from the _nav2\_core::GlobalPlanner_ base class, you have to override the default function definitions. Due to the feature of function overloading in c++, the function definition in the tutorial code is not recognized as an attempt to override the function definition in the base class, as it expects different parameters (_WeakPtr_) than the base class definition in Foxy (_SharedPtr_).

If you adjust the function definition in the tutorial code, you also have to adjust some code in the _configure()_ function. If you replace the line “node\_ = parent.lock();” with “node\_ = parent;” you will be able to build the package successfully (“parent has no member function lock()”). Unfortunately I am not sure what further effects this code adjustment will have.

I am currently struggling with the import of the plugin in the _nav2\_params.yaml_. The planner-server complains that the planner is no valid planner.

**Comment by SteveMacenski** [comment]
> If you adjust the function definition in the tutorial code, you also have to adjust some code in the configure() function. If you replace the line “node_ = parent.lock();” with “node_ = parent;” you will be able to build the package successfully (“parent has no member function lock()”). Unfortunately I am not sure what further effects this code adjustment might have.

None, its equivalent

**Comment by SteveMacenski** [comment]
Closing - solved
