### ISSUE TITLE
unable to build with foxy

### ISSUE THREAD

**Issue by MS71** [ros-planning/navigation2_tutorials#24]
When building with foxy, i get some build errors.

Fixed with attached patch.
[navigation2_tutorials.patch.txt](https://github.com/ros-planning/navigation2_tutorials/files/6214147/navigation2_tutorials.patch.txt)

**Comment by SteveMacenski** [comment]
Nav2 documentation tracks ROS2 master, sorry, we don't currently have the developer cycles to update for each specific distribution.
