### ISSUE TITLE
Incorrect inertia and caster radius setting in sam_bot_description.urdf

### ISSUE THREAD

**Issue by liangyuwei-ai** [ros-planning/navigation2_tutorials#26]
Inertia settings and caster wheel radius setting in `sam_bot_description/src/description/sam_bot_description.urdf` are not properly set, yielding weird behavior when the robot is loaded in Gazebo.

1. The calculation of moment of inertia is right, according to Wiki, but the local frame is inconsistent with that of the Wiki's results, thus a transform is required.
e.g. 
```xml
<xacro:macro name="box_inertia" params="m w h d">
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
      <mass value="${m}"/>
      <inertia ixx="${(m/12) * (h*h + d*d)}" ixy="0.0" ixz="0.0" iyy="${(m/12) * (w*w + d*d)}" iyz="0.0" izz="${(m/12) * (w*w + h*h)}"/>
    </inertial>
</xacro:macro>
```
![issue1](https://user-images.githubusercontent.com/81143085/116253477-1ba15d80-a7a3-11eb-8329-e2b9e0110682.png)

2. Caster wheel radius is somehow set to negative... so the front_caster link would sink under the plane when viewed in Gazebo.
```xml
<geometry>
        <sphere radius="${-(wheel_radius+wheel_zoff-(base_height/2))}"/>
</geometry>
```
![issue2](https://user-images.githubusercontent.com/81143085/116254021-936f8800-a7a3-11eb-902c-eedff079cf17.png)

**Comment by SteveMacenski** [comment]
@jd-deleon  can you verify this is correct and the patch in #27 is OK with you?
