### ISSUE TITLE
Foxy - Build error: class std::shared_ptr<rclcpp_lifecycle::LifecycleNode>’} has no member named ‘lock’

### ISSUE THREAD

**Issue by Yousseflah** [ros-planning/navigation2_tutorials#29]
### I've encountered an error when trying to build the project using colcon build: (Ubuntu 20.04 + Foxy)
stderr: nav2_gradient_costmap_plugin                                                                                                                     
/home/youssef/ros2_ws/src/navigation2_tutorials/nav2_gradient_costmap_plugin/src/gradient_layer.cpp: In member function ‘virtual void nav2_gradient_costmap_plugin::GradientLayer::onInitialize()’:
/home/youssef/ros2_ws/src/navigation2_tutorials/nav2_gradient_costmap_plugin/src/gradient_layer.cpp:70:21: error: ‘using SharedPtr = class std::shared_ptr<rclcpp_lifecycle::LifecycleNode>’ {aka ‘class std::shared_ptr<rclcpp_lifecycle::LifecycleNode>’} has no member named ‘lock’
   70 |   auto node = node_.lock();
      |                     ^~~~
make[2]: *** [CMakeFiles/nav2_gradient_costmap_plugin_core.dir/build.make:63: CMakeFiles/nav2_gradient_costmap_plugin_core.dir/src/gradient_layer.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/nav2_gradient_costmap_plugin_core.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

![lock error](https://user-images.githubusercontent.com/53279766/117197858-4fd5d900-adb6-11eb-82c2-a2559cf9418e.png)

**Comment by SteveMacenski** [comment]
These tutorials are for main branch, which uses weak pointers not shared pointers for the API. You can resolve simply by removing those lines.
