### ISSUE TITLE
Path Planner not responding 

### ISSUE THREAD

**Issue by AlaaAlassi** [ros-planning/navigation2_tutorials#31]
### Bug report
I was trying to use nav2_gradient_costmap_plugin as mentioned here:
[https://github.com/ros-planning/navigation2_tutorials/tree/master/nav2_gradient_costmap_plugin](url)

Required Info:

Operating System:
ubuntu20.04

ROS2 Version:
galactic

Version or commit hash:
074d582

### Current Behavior 
When the robot is given a goal position, the planner halt forever, and this is the last message and this is the last message I get
```
[lifecycle_manager-5] [INFO] [1627288921.973608032] [lifecycle_manager_navigation]: Creating bond timer...
[bt_navigator-4] [INFO] [1627288936.097422353] [bt_navigator]: Begin navigating from current location to (1.83, -2.85)
```
### Ideal Behavior: 
The planner should either make a plan if it is possible, or complain that that it is not possible to make a plan to the given position

### Solution 
In file `gradient_layer.cpp` The flag "current_" must be inserted and set to true. 
```
GradientLayer::onInitialize()
{
  auto node = node_.lock(); 
  declareParameter("enabled", rclcpp::ParameterValue(true));
  node->get_parameter(name_ + "." + "enabled", enabled_);

  need_recalculation_ = false;
  current_ = true;
}
```
As I understood, this flag will give an indication to the path planner that the current data of the costmap are up to date.

**Comment by SteveMacenski** [comment]
A PR would be appreciated
