### ISSUE TITLE
Planner plugin - build 

### ISSUE THREAD

**Issue by aghari19** [ros-planning/navigation2_tutorials#36]
Hi, 
I am trying to run the planner plugging in ROS2 Foxy. I am trying to run the straightline_planner [example](https://navigation.ros.org/plugin_tutorials/docs/writing_new_nav2planner_plugin.html) in a workspace but not able to proceed past these two errors. 
This is the github repo I am using: [github](https://github.com/ros-planning/navigation2_tutorials)
![Screenshot from 2021-09-29 15-48-29](https://user-images.githubusercontent.com/47031270/135338500-5c02a79b-c6f2-483a-9c2b-f3961d63d99a.png)

Can someone help with these please?

**Comment by SteveMacenski** [comment]
These tutorials are built for galactic and newer.

**Comment by aghari19** [comment]
I see. Thank you for letting me know about it. 

I have a followup question. I downloaded ROS2 Galactic since the examples are for Galactic and up. After downloading ROS2 Galactic I tried to install and build Nav2 for Galactic. 

When I build Nav2 for source I get the following error on 24/34. 
I did the following things:
I followed the tutorial [here](https://navigation.ros.org/build_instructions/index.html):

When I had to execute the following commands:
![image](https://user-images.githubusercontent.com/47031270/136235452-762e1c39-496d-4b48-ba9e-8f31f32cf68b.png)

I saw on github there was not a galactic-devel branch to clone from. Therefore, I cloned the galactic branch and went ahead with the build. While building the following error was encountered:
![image](https://user-images.githubusercontent.com/47031270/136235975-7b4cd8c6-c612-4ed0-ad47-3bdd10f9f5db.png)

Can someone please help me with this issue or did I clone the wrong branch altogether. I have looked for help online by googling but nothing has worked. 

I truly appreciate the help, 
Thanks,
