### ISSUE TITLE
Follow up - Planner plugin - build #36

### ISSUE THREAD

**Issue by aghari19** [ros-planning/navigation2_tutorials#37]
I have a followup question from the Planner plugin - build #36 issue raised. I downloaded ROS2 Galactic since the examples are for Galactic and up. After downloading ROS2 Galactic I tried to install and build Nav2 for Galactic.

When I build Nav2 for source I get the following error on 24/34.
I did the following things:
I followed the tutorial [here](https://navigation.ros.org/build_instructions/index.html):

When I had to execute the following commands:
![image](https://user-images.githubusercontent.com/47031270/136237330-7adbfd51-8ba1-40f5-9050-cb3c40ceb281.png)

I saw on github there was not a galactic-devel branch to clone from. Therefore, I cloned the galactic branch and went ahead with the build. While building the following error was encountered:
![image](https://user-images.githubusercontent.com/47031270/136237252-acfa3e4c-fe5d-41d4-82ca-d7a48fea7df6.png)

Can someone please help me with this issue or did I clone the wrong branch altogether. I have looked for help online by googling but nothing has worked.

I truly appreciate the help,
Thanks,

**Comment by SteveMacenski** [comment]
Please ask on ROS Answers, you will not get build help in the issue tracker
