### ISSUE TITLE
nav2_pure_pursuit_controller pkg not in master branch

### ISSUE THREAD

**Issue by figoowen2003** [ros-planning/navigation2_tutorials#42]
I cloned the whole repo to my local directory, but I could not find nav2_pure_pursuit_controller pkg in it. I check this pkg on website and find that it could not show in master branch, instead it will appear in a branch named 126902457c5c646b136569886d6325f070c1073d. Will you please deal with it, please? 
![image](https://user-images.githubusercontent.com/12406353/144538964-6b550997-a2be-4ac4-88fd-98776a9acd42.png)
![image](https://user-images.githubusercontent.com/12406353/144539005-6599a49f-0e65-4e0c-9d67-9d1cb7adaf9f.png)

**Comment by SteveMacenski** [comment]
That is deprecated. It's been further developed on and merged into Nav2 proper as a new controller plugin for use https://github.com/ros-planning/navigation2/tree/main/nav2_regulated_pure_pursuit_controller

See our plug documentation and migration guides that cover this extensively https://navigation.ros.org/

**Comment by SteveMacenski** [comment]
I also glanced at your website (figoowen2003.github.io) and it contains a **great deal** of copyright infringement. Please remove blog posts that clearly copy + paste content from our documentation without attribution (or add proper attribution).
