### ISSUE TITLE
Recovery to behavior

### ISSUE THREAD

**Issue by Ryujiyasu** [ros-planning/navigation2_tutorials#53]
I think we need to change the structure of this package.

https://github.com/ros-planning/navigation2/pull/2867

**Comment by SteveMacenski** [comment]
Yes, that is true, we have not been updating the tutorial code from those changes. Would you be open to submitting a PR to make those changes here?

**Comment by Ryujiyasu** [comment]
https://github.com/ros-planning/navigation2_tutorials/pull/54
