### ISSUE TITLE
Error at colcon build in making costmap 2d plugin

### ISSUE THREAD

**Issue by Kushagra-05** [ros-planning/navigation2_tutorials#62]
![Screenshot 2022-08-24 133926](https://user-images.githubusercontent.com/98595254/186394408-8b1ea5de-0fe7-4eff-90ae-f949507f32fc.png)
I am getting 3 errors, firstly, it says that "gradient_layer.hpp: No such file" whereas it exists in the mentioned location.
The other two errors, are CMake ones, please look at the screenshot attached.

**Comment by Kushagra-05** [comment]
The issue came because i was a little confused with two folders with same name, nav2_gradient_costmap_plugin folder has an include folder which again has a nav2_gradient_costmap_plugin folder which has to be the place for gardient_layer.hpp file, exactly the same as github repo shows.
It was my digression that gave the 1st error (in red)

**Comment by Namo98** [comment]
> The issue came because i was a little confused with two folders with same name, nav2_gradient_costmap_plugin folder has an include folder which again has a nav2_gradient_costmap_plugin folder which has to be the place for gardient_layer.hpp file, exactly the same as github repo shows. It was my digression that gave the 1st error (in red)

Hey Kushagra. Did the nav2_gradientcostmap_pliugin works for you?

i tried to add the nav2_gradient_costmap_plugin but the robot can still move:
https://streamable.com/3g2vw8
