### ISSUE TITLE
(Nav2_gps_waypoint_follower) No such file or directory of some library 

### ISSUE THREAD

**Issue by Klein237** [ros-planning/navigation2_tutorials#71]
Thank you for your work on the nav2_gps_waypoint_follower_demo package. To give it a try, I followed this tutorial https://navigation.ros.org/tutorials/docs/navigation2_with_gps.html . 
On my main system, I use a galactic ROS to run the package. 

In part 2 of the tutorial (Setup Navigation system ) , when I run the following command, ros2 launch nav2_gps_waypoint_follower_demo gps_waypoint_follower.launch.py use_rviz:=True 
I get a problem like this:
[bt_navigator-11] [ERROR] [1696270449.894657632] [bt_navigator]: Original error: Could not load library: libnav2_are_error_codes_active_condition_bt_node.so: cannot open shared object file: No such file or directory

this on several libraries, namely :
- nav2_would_a_controller_recovery_help_condition_bt_node  
- nav2_would_a_planner_recovery_help_condition_bt_node  
- nav2_would_a_smoother_recovery_help_condition_bt_node  
- nav2_are_error_codes_active_condition_bt_node  
- nav2_smooth_path_action_bt_node etc..

I thought it was a version problem and I did a docker with Humble to run the package and I got the same errors but this time I removed the following plugins from the nav2 configuration file:
- nav2_would_a_controller_recovery_help_condition_bt_node  
- nav2_would_a_planner_recovery_help_condition_bt_node  
- nav2_would_a_smoother_recovery_help_condition_bt_node  
- nav2_are_error_codes_active_condition_bt_node  

I was able to have autonomous gps navigation.
Can you help me understand what's going on?

**Comment by SteveMacenski** [comment]
Galactic is EOL and will not receive support. Upgrade to a current ROS distribution. 

But in general, you should remove BT nodes that aren't in your distribution from the YAML. There may be other issues you may run into, I'm not sure. But certainly GPS waypoint following is **not** available in Galactic so you won't be able to use the action at all without Humble or newer.
