### ISSUE TITLE
nav2_gps_waypoint_follower_demo does not work on ros2 humble!!!

### ISSUE THREAD

**Issue by ZaBy10** [ros-planning/navigation2_tutorials#75]
Is there any way to make nav2_gps_waypoint_follower_demo package work on ros2 humble????

 or

Is there any way to Navigate using gps localisation on ros2 humble or ros2 foxxy????

**Comment by SteveMacenski** [comment]
This ticket does not contain any amount of necessary detail to be actionable, thus closing. These tutorials target Rolling but is likely to be useful in Humble.

**Comment by ZaBy10** [comment]
Hii @SteveMacenski , Could you please tell me what minor modifications must be made for it to be used in ros2 humble...
Please provide us the solution!!!

**Comment by peakyquest** [comment]
I have implemented the demo in humble and I have created a PR, can you please look at it.
