### ISSUE TITLE
Some changes to facilitate real robot migration

### ISSUE THREAD

**Issue by elgarbe** [ros-planning/navigation2_tutorials#81]
Hi, I'm migrating GPS WP following to a real robot. On it I already have robot_localization dual ekf + navsat node. Obviously I don't need gazebo and as it is headless I will not run rviz there.
So, I have to comment out some lines on [launch file](https://github.com/ros-planning/navigation2_tutorials/blob/master/nav2_gps_waypoint_follower_demo/launch/gps_waypoint_follower.launch.py)
It would be very useful to have gazebo and R_L parameter for condition their execution, like rviz and mapviz. The same for use_sim_time.
Doing that we can use this same package, on a real robot.
I will be testing this on the follow days, do you have interest on have a PR with it?

Thank and best regards

**Comment by SteveMacenski** [comment]
No, this is tutorial code made simple on purpose to be followable.
