### ISSUE TITLE
package building error

### ISSUE THREAD

**Issue by Parikshit01** [ros-planning/navigation2_tutorials#82]
while building the repo i'm having the following error 

![Screenshot from 2024-02-09 00-38-10](https://github.com/ros-planning/navigation2_tutorials/assets/1684250/3a59ac1e-2dbc-4b32-b1cf-ac245f6e3c36)

**Comment by SteveMacenski** [comment]
This repo targets rolling on,y use ROS 2 rolling or you'll need to modify the tutorials for your distribution

**Comment by Parikshit01** [comment]
please share some resource related to the modifications needed to be done for foxy ros2

**Comment by Parikshit01** [comment]
> This repo targets rolling on,y use ROS 2 rolling or you'll need to modify the tutorials for your distribution

please share some resource related to the modifications needed to be done for foxy ros2
