### ISSUE TITLE
Minor change for nav2_costmap_filters_demo for ros2 humble

### ISSUE THREAD

**Issue by kulkarni-raunak** [ros-planning/navigation2_tutorials#99]
A minor change needed in [launch file](https://github.com/ros-navigation/navigation2_tutorials/blob/humble/nav2_costmap_filters_demo/launch/costmap_filter_info.launch.py#L25) for ros2 humble. 

I'll open a PR to resolve it.

**Comment by SteveMacenski** [comment]
LGTM, chat in the PR
